- hosts: all
  gather_facts: true
  vars_files:
    - [ "vars/{{ ansible_facts['os_family'] }}.yaml"]
  environment:
    https_proxy: "{{ http_proxy }}"
    http_proxy: "{{ http_proxy }}"
  tasks:
  - include_role:
      name: create_users
  - include_role:
      name: ftp

