- name: Wait before connecting to host
  wait_for_connection:
    delay: 30
    timeout: 300

## Create ftpuser
- name: Create user
  become: true
  user:
    state: present
    name: "{{ ftp_user }}"
    password: "{{ pass_user | password_hash('sha512') }}"
    shell: /usr/sbin/nologin

## Create default directory for ftpuser
- name: Create FTP home directory
  become: true
  file:
    path: "/etc/vsftpd/users.d/{{ ftp_user }}/ftp"
    state: directory
    mode: a-w
    owner: nobody
    group: nogroup

- name: Create directory for files upload
  become: true
  file:
    path: "/etc/vsftpd/users.d/{{ ftp_user }}/ftp/files"
    state: directory
    owner: "{{ ftp_user }}"
    group: "{{ ftp_user }}"